//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rabbit.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rabbit.Localizations.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log into Armor Games..
        /// </summary>
        internal static string ArmorGamesLogOnFailure {
            get {
                return ResourceManager.GetString("ArmorGamesLogOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Games login is not supported for the specified game..
        /// </summary>
        internal static string ArmorGamesNotSupported {
            get {
                return ResourceManager.GetString("ArmorGamesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Games authentication was chosen because tokens were supplied for the username and password..
        /// </summary>
        internal static string AssumeArmorGamesAuth {
            get {
                return ResourceManager.GetString("AssumeArmorGamesAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook authentication was chosen because a username was not supplied..
        /// </summary>
        internal static string AssumeFacebookAuth {
            get {
                return ResourceManager.GetString("AssumeFacebookAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kongregate authentication was chosen because the tokens were in hexadecimal..
        /// </summary>
        internal static string AssumeKongregateAuth {
            get {
                return ResourceManager.GetString("AssumeKongregateAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email/token, and password fields cannot be blank..
        /// </summary>
        internal static string EmailPasswordNullError {
            get {
                return ResourceManager.GetString("EmailPasswordNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room id url was not recognized. Make sure that the url is valid..
        /// </summary>
        internal static string InvalidRoomUrl {
            get {
                return ResourceManager.GetString("InvalidRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be exactly 64 characters..
        /// </summary>
        internal static string KongregatePasswordTooLong {
            get {
                return ResourceManager.GetString("KongregatePasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be exactly 64 characters..
        /// </summary>
        internal static string KongregatePasswordTooShort {
            get {
                return ResourceManager.GetString("KongregatePasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username must be an integer..
        /// </summary>
        internal static string KongregateUsernameMustBeInteger {
            get {
                return ResourceManager.GetString("KongregateUsernameMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials for Mousebreaker authentication..
        /// </summary>
        internal static string MouseBreakerAuthFailure {
            get {
                return ResourceManager.GetString("MouseBreakerAuthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mousebreaker login is not supported for the specified game..
        /// </summary>
        internal static string MousebreakerNotSupported {
            get {
                return ResourceManager.GetString("MousebreakerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second token must be 32 characters..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second token must be 32 characters..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room ID cannot be null..
        /// </summary>
        internal static string The_room_ID_cannot_be_null {
            get {
                return ResourceManager.GetString("The_room_ID_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token must be longer than 100 characters..
        /// </summary>
        internal static string TokenLessThan100Chars {
            get {
                return ResourceManager.GetString("TokenLessThan100Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token must be alphanumeric..
        /// </summary>
        internal static string TokenMustBeAlphamumeric {
            get {
                return ResourceManager.GetString("TokenMustBeAlphamumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown url..
        /// </summary>
        internal static string unknownUrl {
            get {
                return ResourceManager.GetString("unknownUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url was correct, but the room id was invalid..
        /// </summary>
        internal static string UrlCorrectRoomIDNot {
            get {
                return ResourceManager.GetString("UrlCorrectRoomIDNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username login is not supported for the specified game..
        /// </summary>
        internal static string UsernameNotSupported {
            get {
                return ResourceManager.GetString("UsernameNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first token must be 32 characters..
        /// </summary>
        internal static string UsernameTooLong {
            get {
                return ResourceManager.GetString("UsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first token must be 32 characters..
        /// </summary>
        internal static string UsernameTooShort {
            get {
                return ResourceManager.GetString("UsernameTooShort", resourceCulture);
            }
        }
    }
}
