//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Rabbit {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class strings {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Rabbit.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not log into Armor Games..
        /// </summary>
        internal static string ArmorGamesLogOnFailure {
            get {
                return ResourceManager.GetString("ArmorGamesLogOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Games login is not supported for the specified game..
        /// </summary>
        internal static string ArmorGamesNotSupported {
            get {
                return ResourceManager.GetString("ArmorGamesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Games authentication was chosen because tokens were supplied for the username and password..
        /// </summary>
        internal static string AssumeArmorGamesAuth {
            get {
                return ResourceManager.GetString("AssumeArmorGamesAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook authentication was chosen because a username was not supplied..
        /// </summary>
        internal static string AssumeFacebookAuth {
            get {
                return ResourceManager.GetString("AssumeFacebookAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email/token, and password fields cannot be blank..
        /// </summary>
        internal static string EmailPasswordNullError {
            get {
                return ResourceManager.GetString("EmailPasswordNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room id url was not recognized. Make sure that the url is valid..
        /// </summary>
        internal static string InvalidRoomUrl {
            get {
                return ResourceManager.GetString("InvalidRoomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials for Mousebreaker authentication..
        /// </summary>
        internal static string MouseBreakerAuthFailure {
            get {
                return ResourceManager.GetString("MouseBreakerAuthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mousebreaker login is not supported for the specified game..
        /// </summary>
        internal static string MousebreakerNotSupported {
            get {
                return ResourceManager.GetString("MousebreakerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second token must be 32 characters..
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second token must be 32 characters..
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The room ID cannot be null..
        /// </summary>
        internal static string The_room_ID_cannot_be_null {
            get {
                return ResourceManager.GetString("The_room_ID_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token must be longer than 100 characters..
        /// </summary>
        internal static string TokenLessThan100Chars {
            get {
                return ResourceManager.GetString("TokenLessThan100Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token must be alphanumeric..
        /// </summary>
        internal static string TokenMustBeAlphamumeric {
            get {
                return ResourceManager.GetString("TokenMustBeAlphamumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown url..
        /// </summary>
        internal static string unknownUrl {
            get {
                return ResourceManager.GetString("unknownUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url was correct, but the room id was invalid..
        /// </summary>
        internal static string UrlCorrectRoomIDNot {
            get {
                return ResourceManager.GetString("UrlCorrectRoomIDNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username login is not supported for the specified game..
        /// </summary>
        internal static string UsernameNotSupported {
            get {
                return ResourceManager.GetString("UsernameNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first token must be 32 characters..
        /// </summary>
        internal static string UsernameTooLong {
            get {
                return ResourceManager.GetString("UsernameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first token must be 32 characters..
        /// </summary>
        internal static string UsernameTooShort {
            get {
                return ResourceManager.GetString("UsernameTooShort", resourceCulture);
            }
        }
    }
}
